service: awsbackend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: javodotcom
  region: us-east-1
  stage: talk
  environment:
    FONTCONFIG_PATH: /opt/fonts
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: !Sub 'arn:aws:s3:::${S3PDFBucket}/*'

layers:
  wkhtmltoxLayer:
    name: wkhtmltox
    description: wkhtmltox binaries for pdf/image generation
    package:
      artifact: layers/wkhtmltox-0.12.6-4.amazonlinux2_lambda.zip

functions:
    PdfGenerator:
        handler: src/generatePdf.handler
        layers:
            - { Ref: WkhtmltoxLayerLambdaLayer }
        environment:
            FONTCONFIG_PATH: /opt/fonts
            BUCKET_NAME: !Ref S3PDFBucket
        events:
            - http:
                path: create-pdf
                method: post
                cors: true

resources:
    Resources:
        S3PDFBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: javodotcom-pdf
                AccessControl: PublicRead
                CorsConfiguration:
                    CorsRules:
                        - AllowedHeaders:
                            - '*'
                          AllowedMethods:
                            - GET
                            - POST
                            - PUT
                          AllowedOrigins:
                            - '*'
                          MaxAge: 3000
                PublicAccessBlockConfiguration:
                    BlockPublicAcls: true
                    BlockPublicPolicy: true
                    IgnorePublicAcls: true
                    RestrictPublicBuckets: true
                VersioningConfiguration:
                    Status: Enabled
package:
  patterns:
    - '!layers/**'